### ISSUE TITLE
"Load/save module" feature needed

### ISSUE THREAD

**Issue by Drayldan** [epi/enotracker#1]
Hi Epi(j), would you be so kind and add much needed **load/save music** (ready-made) feature into Enotracker? 
The project looks sooo promising, please keep it up! :)

Cheers,
D.

**Comment by epi** [comment]
Hi @Drayldan, please check 9880595. Windows executable also attached.
[enotracker-0.1.1-windows-x86_64.zip](https://github.com/epi/enotracker/files/5750830/enotracker-0.1.1-windows-x86_64.zip)

Keys:
- CTRL+S saves under current name
- CTRL+SHIFT+S opens "Save as" dialog
- CTRL+L opens "Open" dialog

**Comment by Drayldan** [comment]
Gr8t! Thanx for your update, now is far better.
What I'd report is: 
- lack of quit from program (to add)
- program sometimes locks up when loading and playing some tunes (buffer is not cleared every time?)
- should track with notes from lower part can  be animated  when playing whole tune (just like in old good Amiga's ProTracker) ? ;)
